const { ethers, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

const OFFICIAL_USDT = "0x75edC9335175Fc0552D51D48439F229c10420fe3";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log(`Deploying from ${deployer.address} on ${network.name}`);

  let usdt = process.env.USDT_ADDRESS || OFFICIAL_USDT;
  if (network.name === "hardhat" || network.name === "localhost") {
    const mock = await (await ethers.getContractFactory("MockUSDT")).deploy();
    await mock.waitForDeployment();
    usdt = mock.target;
    console.log(`MockUSDT: ${usdt}`);
  }

  const treasury = process.env.TREASURY || deployer.address;
  const feeBps = Number(process.env.FEE_BPS ?? 100);

  const SubSafe = await ethers.getContractFactory("SubSafe");
  const safe = await SubSafe.deploy(usdt, treasury, feeBps);
  await safe.waitForDeployment();
  console.log(`SubSafe:  ${safe.target}`);
  console.log(`USDT:     ${usdt}`);
  console.log(`Explorer: https://scan.bohr.life/address/${safe.target}`);

  // Write the address + ABI straight into the Next.js frontend
  const artifact = await require("hardhat").artifacts.readArtifact("SubSafe");
  const out = path.join(__dirname, "../../web/src/lib/contract.ts");
  fs.writeFileSync(
    out,
    `// Auto-generated by contracts/scripts/deploy.js — do not edit by hand\n` +
      `export const SUBSAFE_ADDRESS: \`0x\${string}\` = "${safe.target}";\n` +
      `export const USDT_ADDRESS: \`0x\${string}\` = "${usdt}";\n` +
      `export const SUBSAFE_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`
  );
  console.log(`Wrote ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
