const { ethers, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

// Official USDT per BOT Chain network (both 6 decimals)
const OFFICIAL_USDT = {
  botchain: "0x75edC9335175Fc0552D51D48439F229c10420fe3", // testnet (968), faucet token
  botchainMainnet: "0xaBabc7Ddc03e501d190C676BF3d92ef0e6e87a3C", // mainnet (677)
};
const EXPLORERS = { botchain: "https://scan.bohr.life", botchainMainnet: "https://scan.botchain.ai" };

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log(`Deploying from ${deployer.address} on ${network.name}`);

  let usdt = OFFICIAL_USDT[network.name] || process.env.USDT_ADDRESS;
  if (network.name === "hardhat" || network.name === "localhost") {
    const mock = await (await ethers.getContractFactory("MockUSDT")).deploy();
    await mock.waitForDeployment();
    usdt = mock.target;
    console.log(`MockUSDT: ${usdt}`);
  }

  const treasury = process.env.TREASURY || deployer.address;
  const feeBps = Number(process.env.FEE_BPS ?? 100);

  const SubSafe = await ethers.getContractFactory("SubSafe");
  const safe = await SubSafe.deploy(usdt, treasury, feeBps);
  await safe.waitForDeployment();
  console.log(`SubSafe:  ${safe.target}`);
  console.log(`USDT:     ${usdt}`);
  console.log(`Explorer: ${EXPLORERS[network.name] || "(local)"}/address/${safe.target}`);

  // Hand admin rights (fee settings) to the project owner's own wallet if given
  if (process.env.OWNER) {
    await (await safe.transferOwnership(process.env.OWNER)).wait();
    console.log(`Owner:    ${process.env.OWNER}`);
  }

  // Write the address + ABI straight into the Next.js frontend
  const artifact = await require("hardhat").artifacts.readArtifact("SubSafe");
  const out = path.join(__dirname, "../../web/src/lib/contract.ts");
  fs.writeFileSync(
    out,
    `// Auto-generated by contracts/scripts/deploy.js — do not edit by hand\n` +
      `export const SUBSAFE_ADDRESS: \`0x\${string}\` = "${safe.target}";\n` +
      `export const USDT_ADDRESS: \`0x\${string}\` = "${usdt}";\n` +
      `export const CHAIN_ID: number = ${network.config.chainId ?? 31337};\n` +
      `export const SUBSAFE_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`
  );
  console.log(`Wrote ${out}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
